////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated. 
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace ss222yw_Projekt.Account
//{


//    public partial class Login
//    {

//        /// <summary>
//        /// RegisterHyperLink control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.HyperLink RegisterHyperLink;

//        /// <summary>
//        /// OpenAuthLogin control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::ss222yw_Projekt.Account.OpenAuthProviders OpenAuthLogin;
//    }
//}
